version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - discovery.seed_hosts=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  postgres-data:
  data01:
    driver: local

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge
